[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

  [functions.node_bundler]
    format = "esm"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
