[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

  [functions.node_bundler]
    format = "esm" # enables ES module support for top-level await and import.meta

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
